name: Generate Flutter Design Tokens

on:
  push:
    branches: [main]
    paths:
      - "tokens/tokens.json"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3."

      - name: Install dependencies
        run: flutter pub get

      - name: Run token generator
        run: dart run tool/token_generator.dart

      - name: Commit updated colors.dart
        run: |
          git config user.name "Token Bot"
          git config user.email "bot@miny.dev"
          git add lib/src/tokens/colors.dart
          git commit -m "chore: update colors.dart from tokens" || echo "No changes to commit"
          git push
